Repository se2-carcassonne-team/app, pull requests merged in 2024-04, with the labels that each got.

#3 Philipp frontend basics username selection
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle
  app/src/androidTest/java/se2/carcassonne/ExampleInstrumentedTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/se2/carcassonne/ChooseUsernameDialogFragment.java
  app/src/main/java/se2/carcassonne/GameLobbyActivity.java
  app/src/main/java/se2/carcassonne/HomeActivity.java
  app/src/main/java/se2/carcassonne/StartupActivity.java
  app/src/main/java/se2/carcassonne/gamelobby/model/GameLobby.java
  app/src/main/java/se2/carcassonne/helper/network/WebSocketClient.java
  app/src/main/java/se2/carcassonne/helper/network/WebSocketMessageHandler.java
  app/src/main/java/se2/carcassonne/helper/resize/FullscreenHelper.java
  app/src/main/java/se2/carcassonne/player/model/Player.java
  app/src/main/java/se2/carcassonne/player/repository/PlayerApi.java
  app/src/main/java/se2/carcassonne/player/repository/PlayerRepository.java
  app/src/main/java/se2/carcassonne/player/viewmodel/ChooseUsernameViewModel.java
  app/src/main/res/drawable/carcassonne_logo.png
  app/src/main/res/drawable/carcassonne_title.png
  app/src/main/res/drawable/custom_input.xml
  app/src/main/res/drawable/home_background.png
  app/src/main/res/drawable/startup_background.jpg
  app/src/main/res/font/almendra_sc.xml
  app/src/main/res/layout/game_lobby_activity.xml
  app/src/main/res/layout/home_activity.xml
  app/src/main/res/layout/startup_activity.xml
  app/src/main/res/layout/username_dialog.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/button_styles.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/preloaded_fonts.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
  settings.gradle
Labels: enhancement

#14 Amadeo list users in lobby ver3
  .gitignore
  .idea/.gitignore
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/se2/carcassonne/ChooseUsernameDialogFragment.java
  app/src/main/java/se2/carcassonne/CreateLobbyDialog.java
  app/src/main/java/se2/carcassonne/GameLobbyActivity.java
  app/src/main/java/se2/carcassonne/InLobbyActivity.java
  app/src/main/java/se2/carcassonne/LobbyListsActivity.java
  app/src/main/java/se2/carcassonne/lobby/model/Lobby.java
  app/src/main/java/se2/carcassonne/lobby/repository/LobbyApi.java
  app/src/main/java/se2/carcassonne/lobby/repository/LobbyRepository.java
  app/src/main/java/se2/carcassonne/lobby/viewmodel/LobbyListAdapter.java
  app/src/main/java/se2/carcassonne/lobby/viewmodel/LobbyListViewModel.java
  app/src/main/java/se2/carcassonne/lobby/viewmodel/PlayersInLobbyListAdapter.java
  app/src/main/res/drawable/person_icon.xml
  app/src/main/res/layout/create_lobby_dialog.xml
  app/src/main/res/layout/in_lobby_activity.xml
  app/src/main/res/layout/text_player_in_lobby_item_row.xml
  app/src/main/res/layout/username_dialog.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#19 Unsubscribing from Topics
  .gitignore
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  app/build.gradle
  app/src/main/java/se2/carcassonne/ChooseUsernameDialogFragment.java
  app/src/main/java/se2/carcassonne/CreateLobbyDialog.java
  app/src/main/java/se2/carcassonne/GameLobbyActivity.java
  app/src/main/java/se2/carcassonne/GameboardAdapter.java
  app/src/main/java/se2/carcassonne/HomeActivity.java
  app/src/main/java/se2/carcassonne/InLobbyActivity.java
  app/src/main/java/se2/carcassonne/LobbyListsActivity.java
  app/src/main/java/se2/carcassonne/StartupActivity.java
  app/src/main/java/se2/carcassonne/ZoomFunction.java
  app/src/main/java/se2/carcassonne/helper/mapper/MapperHelper.java
  app/src/main/java/se2/carcassonne/helper/network/WebSocketClient.java
  app/src/main/java/se2/carcassonne/lobby/model/Lobby.java
  app/src/main/java/se2/carcassonne/lobby/repository/LobbyApi.java
  app/src/main/java/se2/carcassonne/lobby/repository/LobbyRepository.java
  app/src/main/java/se2/carcassonne/lobby/viewmodel/LobbyListAdapter.java
  app/src/main/java/se2/carcassonne/lobby/viewmodel/LobbyListViewModel.java
  app/src/main/java/se2/carcassonne/lobby/viewmodel/LobbyViewModel.java
  app/src/main/java/se2/carcassonne/lobby/viewmodel/PlayerListAdapter.java
  app/src/main/java/se2/carcassonne/player/model/Player.java
  app/src/main/java/se2/carcassonne/player/repository/PlayerApi.java
  app/src/main/java/se2/carcassonne/player/repository/PlayerRepository.java
  app/src/main/java/se2/carcassonne/player/viewmodel/ChooseUsernameViewModel.java
  app/src/main/java/se2/carcassonne/player/viewmodel/PlayerViewModel.java
  settings.gradle
Labels: enhancement, bugfix

#24 Lobby Admin Feature
  app/src/main/java/se2/carcassonne/InLobbyActivity.java
  app/src/main/java/se2/carcassonne/helper/mapper/MapperHelper.java
  app/src/main/java/se2/carcassonne/lobby/model/GameState.java
  app/src/main/java/se2/carcassonne/lobby/model/Lobby.java
  app/src/main/java/se2/carcassonne/lobby/repository/LobbyApi.java
  app/src/main/java/se2/carcassonne/lobby/repository/LobbyRepository.java
  app/src/main/java/se2/carcassonne/lobby/viewmodel/LobbyListAdapter.java
  app/src/main/java/se2/carcassonne/lobby/viewmodel/LobbyViewModel.java
  app/src/main/java/se2/carcassonne/player/model/Player.java
  app/src/main/res/layout/in_lobby_activity.xml
  settings.gradle
Labels: enhancement

#27 Start game with more than two players
  app/src/main/java/se2/carcassonne/InLobbyActivity.java
  app/src/main/java/se2/carcassonne/lobby/model/GameState.java
  app/src/main/java/se2/carcassonne/lobby/repository/LobbyRepository.java
Labels: enhancement

#28 Wrong Endpoint for starting game in LobbyApi
  app/src/main/java/se2/carcassonne/lobby/repository/LobbyApi.java
Labels: bugfix

#30 feat: a crown is always displayed for the current lobby admin
  app/src/main/java/se2/carcassonne/InLobbyActivity.java
  app/src/main/java/se2/carcassonne/lobby/repository/LobbyRepository.java
  app/src/main/java/se2/carcassonne/lobby/viewmodel/PlayerListAdapter.java
  app/src/main/res/drawable/admin_crown.png
  app/src/main/res/layout/text_player_in_lobby_item_row.xml
Labels: enhancement
