Repository se2-carcassonne-team/app, pull requests merged in 2024-05, with the labels that each got.

#43 Highlighting- & Rotating- & Placing Tiles
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  README.md
  app/src/main/java/se2/carcassonne/api/GameSessionApi.java
  app/src/main/java/se2/carcassonne/model/Coordinates.java
  app/src/main/java/se2/carcassonne/model/GameBoard.java
  app/src/main/java/se2/carcassonne/model/NextTurn.java
  app/src/main/java/se2/carcassonne/model/PlacedTileDto.java
  app/src/main/java/se2/carcassonne/model/Player.java
  app/src/main/java/se2/carcassonne/model/Tile.java
  app/src/main/java/se2/carcassonne/repository/GameSessionRepository.java
  app/src/main/java/se2/carcassonne/ui/ChooseUsernameDialogFragment.java
  app/src/main/java/se2/carcassonne/ui/GameBoardActivity.java
  app/src/main/java/se2/carcassonne/ui/GameboardAdapter.java
  app/src/main/java/se2/carcassonne/ui/ImageRotator.java
  app/src/main/java/se2/carcassonne/ui/InLobbyActivity.java
  app/src/main/java/se2/carcassonne/ui/StartupActivity.java
  app/src/main/java/se2/carcassonne/ui/ZoomFunction.java
  app/src/main/java/se2/carcassonne/viewmodel/GameSessionViewModel.java
  app/src/main/java/se2/carcassonne/viewmodel/LobbyViewModel.java
  app/src/main/res/drawable/background_right_2.png
  app/src/main/res/drawable/meeple_blue.png
  app/src/main/res/layout/gameboard_activity.xml
  app/src/main/res/layout/lobby_list_activity.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/GameBoardModelTests.java
  app/src/test/java/TileModelTests.java
Labels: enhancement

#44 fix: eaveLobby call in onDestroy leading to null pointers - Button Rotation
  app/src/main/java/se2/carcassonne/ui/GameBoardActivity.java
  app/src/main/java/se2/carcassonne/ui/InLobbyActivity.java
Labels: bugfix

#52 Dev meeple fixes
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/se2/carcassonne/helper/mapper/MapperHelper.java
  app/src/main/java/se2/carcassonne/model/Lobby.java
  app/src/main/java/se2/carcassonne/model/Meeple.java
  app/src/main/java/se2/carcassonne/model/PlacedTileDto.java
  app/src/main/java/se2/carcassonne/model/Player.java
  app/src/main/java/se2/carcassonne/model/PlayerColour.java
  app/src/main/java/se2/carcassonne/model/PointCalculator.java
  app/src/main/java/se2/carcassonne/model/Tile.java
  app/src/main/java/se2/carcassonne/model/TileInitializer.java
  app/src/main/java/se2/carcassonne/repository/LobbyRepository.java
  app/src/main/java/se2/carcassonne/ui/ChooseUsernameDialogFragment.java
  app/src/main/java/se2/carcassonne/ui/GameBoardActivity.java
  app/src/main/java/se2/carcassonne/ui/GameboardAdapter.java
  app/src/main/java/se2/carcassonne/ui/MeepleAdapter.java
  app/src/main/res/drawable/meeple_black.png
  app/src/main/res/drawable/meeple_blue.png
  app/src/main/res/drawable/meeple_green.png
  app/src/main/res/drawable/meeple_red.png
  app/src/main/res/drawable/meeple_road.png
  app/src/main/res/drawable/meeple_yellow.png
  app/src/main/res/layout/gameboard_activity.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/GameBoardModelTests.java
  app/src/test/java/TileModelTests.java
Labels: enhancement

#55 Joystick UI
  app/build.gradle
  app/src/main/java/se2/carcassonne/ui/GameBoardActivity.java
  app/src/main/java/se2/carcassonne/ui/InLobbyActivity.java
  app/src/main/java/se2/carcassonne/viewmodel/PlayerListAdapter.java
  app/src/main/res/anim/pulse.xml
  app/src/main/res/anim/scale.xml
  app/src/main/res/drawable/arrow_left.png
  app/src/main/res/drawable/arrow_right.png
  app/src/main/res/drawable/background_for_meeple_score.png
  app/src/main/res/drawable/button_down.png
  app/src/main/res/drawable/button_left.png
  app/src/main/res/drawable/button_right.png
  app/src/main/res/drawable/button_up.png
  app/src/main/res/drawable/confirm_button.png
  app/src/main/res/drawable/confirm_button_green.png
  app/src/main/res/drawable/joystick_background.png
  app/src/main/res/drawable/joystick_background_two.png
  app/src/main/res/drawable/joystick_face.png
  app/src/main/res/drawable/zoom_minus.png
  app/src/main/res/drawable/zoom_plus.png
  app/src/main/res/layout/gameboard_activity.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/ids.xml
  gradle/libs.versions.toml
  settings.gradle
Labels: enhancement

#56 Vibrator implementation
  app/src/main/AndroidManifest.xml
  app/src/main/java/se2/carcassonne/ui/GameBoardActivity.java
  app/src/main/java/se2/carcassonne/ui/StartupActivity.java
  app/src/main/java/se2/carcassonne/viewmodel/PlayerListAdapter.java
  app/src/main/res/layout/startup_activity.xml
Labels: enhancement

#57 Road & Meeple Logic for Roads
  app/src/main/java/se2/carcassonne/model/GameBoard.java
  app/src/main/java/se2/carcassonne/model/PointCalculator.java
  app/src/main/java/se2/carcassonne/model/RoadResult.java
  app/src/main/java/se2/carcassonne/model/Tile.java
  app/src/main/java/se2/carcassonne/model/TileInitializer.java
  app/src/main/java/se2/carcassonne/ui/GameBoardActivity.java
  app/src/main/java/se2/carcassonne/ui/MeepleAdapter.java
  app/src/main/res/drawable/road_occupied.png
  app/src/test/java/GameBoardModelTests.java
  app/src/test/java/PointCalculatorModelTests.java
  app/src/test/java/TileModelTests.java
Labels: enhancement

#62 Some more SonarCloud Issue Fixes
  app/src/main/java/se2/carcassonne/model/TileInitializer.java
  app/src/main/java/se2/carcassonne/repository/LobbyRepository.java
  app/src/main/java/se2/carcassonne/repository/PlayerRepository.java
  app/src/main/java/se2/carcassonne/ui/GameBoardActivity.java
  app/src/main/java/se2/carcassonne/ui/GameboardAdapter.java
  app/src/main/java/se2/carcassonne/ui/HomeActivity.java
  app/src/main/java/se2/carcassonne/viewmodel/GameSessionViewModel.java
  app/src/main/java/se2/carcassonne/viewmodel/LobbyViewModel.java
  app/src/main/java/se2/carcassonne/viewmodel/PlayerViewModel.java
Labels: bugfix

#61 Fix SonarCloud Issues Part 1
  app/src/main/java/se2/carcassonne/api/GameSessionApi.java
  app/src/main/java/se2/carcassonne/api/LobbyApi.java
  app/src/main/java/se2/carcassonne/api/PlayerApi.java
  app/src/main/java/se2/carcassonne/helper/animation/AnimationHelper.java
  app/src/main/java/se2/carcassonne/helper/mapper/MapperHelper.java
  app/src/main/java/se2/carcassonne/helper/network/WebSocketClient.java
Labels: bugfix

#63 Amadeo lobby hide merge
  app/src/main/java/se2/carcassonne/ui/GameBoardActivity.java
  app/src/main/java/se2/carcassonne/ui/InLobbyActivity.java
  app/src/main/java/se2/carcassonne/viewmodel/LobbyListAdapter.java
  app/src/main/res/anim/pulse.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, bugfix

#64 fix: button text startGame is no more visible, after all except from …
  app/src/main/java/se2/carcassonne/ui/InLobbyActivity.java
Labels: bugfix

#65 (potentially) fixed bug: app crashed sometimes when joining a lobby
  app/src/main/AndroidManifest.xml
  app/src/main/java/se2/carcassonne/ui/GameLobbyActivity.java
  app/src/main/java/se2/carcassonne/ui/LobbyListActivity.java
  app/src/main/java/se2/carcassonne/viewmodel/PlayerListAdapter.java
Labels: bugfix

#70 bugfix: Check for no valid tile placement positions
  app/src/main/java/se2/carcassonne/model/GameBoard.java
  app/src/main/java/se2/carcassonne/ui/GameBoardActivity.java
  app/src/test/java/GameBoardModelTests.java
Labels: bugfix
